// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";
// import LargeNav from "./(root)/_components/LargeNav";

// // Importing custom fonts with localFont
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// // Metadata for the page
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// // RootLayout component to structure the page layout
// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#161925]`}
//       >
//         <main className=" overflow-auto ">
//           <div className="flex h-screen ">
//             <div className="lg:w-[16%] md:w-[17%] sm:w-none w-none h-[100vh] pt-10 px-3 border-r border-r-gray-500 sticky top-0 left-0 lg:block md:block sm:hidden hidden">
//               <LargeNav />
//             </div>
//             <section className="flex min-h-screen flex-1 flex-col px-6 pb-6  max-md:pb-14 sm:px-14">
//               {children}
//             </section>
//           </div>
//         </main>
//       </body>
//     </html>
//   );
// }

// {
//   /* <div className="lg:w-[16%] md:w-[17%] sm:w-none w-none h-[100vh] pt-10 px-3 border-r border-r-gray-500 sticky top-0 left-0 lg:block md:block sm:hidden hidden">
//           <LargeNav />
//         </div> */
// }

import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import LargeNav from "./_components/LargeNav";
import MobileNav from "./_components/MobileNav";

// Importing custom fonts with localFont
const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the page
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// justify-between

// RootLayout component to structure the page layout
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#161925]`}
        >
          <div className="w-full h-auto flex items-start  lg:gap-x-32 md:gap-x-16 sm:gap-x-8 gap-x-4 relative">
            <div className="lg:w-[16%] md:w-[17%] sm:w-none w-none h-[100vh] pt-10 px-3 border-r border-r-gray-500 sticky top-0 left-0 lg:block md:block sm:hidden hidden">
              <LargeNav />
            </div>

            {/* Cotton Navbar small screen */}
            <div className="w-full h-auto py-1 px-3 border-t border-t-[#1d1d1d] fixed bottom-0 left-0 lg:hidden md:hidden sm:block block bg-black z-50">
              <MobileNav />
            </div>

            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}

{
  /* <div className="lg:w-[16%] md:w-[17%] sm:w-none w-none h-[100vh] pt-10 px-3 border-r border-r-gray-500 sticky top-0 left-0 lg:block md:block sm:hidden hidden">
          <LargeNav />
        </div> */
}
